fully working and tested
Team1619/uacr-robot-core pull request #45
Opened 2021-02-11 03:55 UTC by HarrisonKaufman

2021-02-12 02:39 UTC, bdupras submitted a review, later dismissed
From what I can tell, this looks like all renames.

2021-02-12 16:22 UTC, coychanders reviewed
Thanks for moving forward on this project. You are getting closer. I found a number of minor things and one major issue that I am confused about. If I read the code correctly, it does not look like you are actually storing the flags. Let me know if you have any questions. Also, please create a branch for you tests so I can run them. That will help me better understand if I am misreading the code or not. We can always delete that branch instead of merging it in.

2021-02-12 16:22 UTC, coychanders commented on src/main/java/org/uacr/models/inputs/numeric/InputNumeric.java
> +    public abstract void processFlags(Set<String> flag);
flags instead of flag

2021-02-12 16:22 UTC, coychanders commented on src/main/java/org/uacr/models/outputs/bool/OutputBoolean.java
> +    public abstract void processFlags(Set<String> flag);
flags instead of flag

2021-02-12 16:22 UTC, coychanders commented on src/main/java/org/uacr/services/input/InputService.java
> +            inputBoolean.processFlags(fSharedInputValues.getInputFlag(name));
Should this be getInputFlags instead of getInputFlag

2021-02-12 16:22 UTC, coychanders commented on src/main/java/org/uacr/services/input/InputService.java
> +            inputNumeric.processFlags(fSharedInputValues.getInputFlag(name));
getInputFlags

2021-02-12 16:22 UTC, coychanders commented on src/main/java/org/uacr/shared/abstractions/InputValues.java
> +    Set<String> getInputFlag(String name);
getInputFlags

2021-02-12 16:22 UTC, coychanders commented on src/main/java/org/uacr/shared/concretions/SharedInputValues.java
> +    public Set<String> getInputFlag(String name) {
getInputFlags

2021-02-12 16:22 UTC, coychanders commented on src/main/java/org/uacr/shared/concretions/SharedOutputValues.java
> +        fOutputFlags.get(name);    }
Again, shouldn't this be storing the value of flag?

2021-02-14 05:30 UTC, bdupras commented on src/main/java/org/uacr/shared/abstractions/InputValues.java
> +    Set<String> getInputFlag(String name);
@HarrisonKaufman looks like we didn't get to this comment from @coychanders ^^

2021-02-18 01:52 UTC, bdupras requested changes

2021-02-18 01:52 UTC, bdupras commented on src/main/java/org/uacr/shared/concretions/SharedInputValues.java
> +        Set<String> flags = fInputFlags.getOrDefault(name, Set.of());
If you look at the javadoc for [Set.of()](https://docs.oracle.com/javase/9/docs/api/java/util/Set.html#of-E...-), it was added in Java 9. uacr-robot-core is configured to be compatible with (Java 1.8)[https://github.com/Team1619/uacr-robot-core/blob/master/build.gradle#L7-L8] to remain compatible with FTC's android framework. 

Since you're just returning an empty set, check out the helper methods on [java.util.Collections](https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html) that are available since Java 1.5.

2021-02-18 03:37 UTC, bdupras submitted a review, later dismissed

2021-02-18 05:17 UTC, coychanders reviewed
Looking much better! Just found one small thing.

2021-02-18 05:17 UTC, coychanders commented on src/main/java/org/uacr/shared/concretions/SharedInputValues.java
> +    public Set<String> getInputFlag(String name) {
This should probably be getInputFlags to be consistant with the SharedOutputValues and with the fact that it returns a set of flags.

2021-02-21 00:28 UTC, coychanders approved these changes

2021-02-21 14:20 UTC, bdupras approved these changes

2021-02-21 14:24 UTC, merged