Af robot status
Team1619/uacr-robot-core pull request #50
Opened 2021-03-04 03:22 UTC by 18fongcgit

adds method to robot status and robot manager allowing our code to decide path based off of limelight data to run when disabled

2021-03-07 21:48 UTC, coychanders approved these changes

2021-03-08 03:08 UTC, MatthewOates36 requested changes

2021-03-08 03:08 UTC, MatthewOates36 commented on src/main/java/org/uacr/robot/RobotManager.java
> +    public void updateStatus() {
What is the purpose of this method?

2021-03-08 03:14 UTC, MatthewOates36 commented on src/main/java/org/uacr/robot/AbstractRobotStatus.java
> +    public void updateWhenDisabled() {
Would it make sense to rename this to disabledUpdate() to follow framework naming conventions?

2021-03-08 19:47 UTC, coychanders approved these changes

2021-03-18 02:22 UTC, bdupras approved these changes

2021-03-18 02:25 UTC, merged